describe('CityTouristER E2E Testing', function(){
    it('Create User', function(){
        cy.contains('Usuarios').click()
        cy.contains('Añadir usuario').click()
        cy.get('#name')
            .type('Andre')
            .should('have.value', 'Andre')
        cy.get('#last_name')
            .type('Rodriguez')
            .should('have.value', 'Rodriguez')
        cy.get('#email')
            .type('andre@gmail.com')
            .should('have.value', 'andre@gmail.com')
        cy.get('#password')
            .type('chilaquiles1')
            .should('have.value', 'chilaquiles1')
        cy.get('#birth')
            .type('1990-01-01')
            .should('have.value', '1990-01-01')
        cy.get('#phone_number')
            .type('2222222222')
            .should('have.value', '2222222222')
        cy.get('#postal_code')
            .type('77777')
            .should('have.value', '77777')
        cy.get('#usertype').select('Cliente')
        cy.contains('Crea Usuario').click()
    })
})