describe('CityTouristER E2E Testing', function(){
    it('Create Stops', function(){
        cy.visit('http://localhost:3000/paradas')
        cy.visit('http://localhost:3000/paradas/agregar')
        cy.get('#name')
            .type('Africam Safari')
            .should('have.value', 'Africam Safari')
        cy.get('#longitude')
            .type('18.937163')
            .should('have.value', '18.937163')
        cy.get('#latitude')
            .type('-98.136907')
            .should('have.value', '-98.136907')
        cy.get('#description')
            .type('Visita al parque Africam Safari')
            .should('have.value', 'Visita al parque Africam Safari')
        cy.get('#image')
            .type('https://storage.googleapis.com/principal-arena-219118/asstop.jpg')
            .should('have.value', 'https://storage.googleapis.com/principal-arena-219118/asstop.jpg')
        cy.contains('Crea Parada').click()

        cy.visit('http://localhost:3000/paradas')
        cy.visit('http://localhost:3000/paradas/agregar')
        cy.get('#name')
            .type('Zocalo')
            .should('have.value', 'Zocalo')
        cy.get('#longitude')
            .type('19.043289')
            .should('have.value', '19.043289')
        cy.get('#latitude')
            .type('-98.198301')
            .should('have.value', '-98.198301')
        cy.get('#description')
            .type('Zocalo de Puebla, partida del tour y finalizacion')
            .should('have.value', 'Zocalo de Puebla, partida del tour y finalizacion')
        cy.get('#image')
            .type('https://storage.googleapis.com/principal-arena-219118/zocalo.jpg')
            .should('have.value', 'https://storage.googleapis.com/principal-arena-219118/zocalo.jpg')
        cy.contains('Crea Parada').click()
    })
})