describe('CityTouristER E2E Testing', function(){
    it('Create Places', function(){
        cy.visit('http://localhost:3000/lugares')
        cy.visit('http://localhost:3000/lugares/tipolugar')
        cy.visit('http://localhost:3000/lugares/tipolugaragregar')
        cy.get('#name')
            .type('Convenio')
            .should('have.value', 'Convenio')
        cy.contains('Crea Tipo de Lugar').click()
        cy.visit('http://localhost:3000/lugares')
        cy.visit('http://localhost:3000/lugares/agregar')
        cy.get('#place_type').select('2')
        cy.get('#narrative').select('2')
        cy.get('#name')
            .type('Gotcha Paintball Turoks')
            .should('have.value', 'Gotcha Paintball Turoks')
        cy.get('#longitude')
            .type('-98.149191')
            .should('have.value', '-98.149191')
        cy.get('#latitude')
            .type('18.951725')
            .should('have.value', '18.951725')
        cy.get('#desc')
            .type('Convenio')
            .should('have.value', 'Convenio')
        cy.contains('Crea Lugar').click()  
    })
})