describe('CityTouristER E2E Testing', function(){
    it('Create Mural', function(){
        cy.visit('http://localhost:3000/mural')
        cy.visit('http://localhost:3000/mural/agregar')
        cy.get('#title')
            .type('Sueño de una tarde dominical en la Alameda Central')
            .should('have.value', 'Sueño de una tarde dominical en la Alameda Central')
        cy.get('#author_name')
            .type('Diego')
            .should('have.value','Diego')
        cy.get('#author_last_name')
            .type('Rivera')
            .should('have.value', 'Rivera')
        cy.get('#desc')
            .type('El primero hace referencia a la Conquista de México, la evangelización, la colonia, la Independencia de México, la Invasión Norteamericana, el gobierno de Santa Anna, la Intervención Francesa y la Reforma. El segundo se refiere a tres figuras centrales: el autoretrato de Diego Rivera a los 9 años, la Catrina y a José Guadalupe Posada. Diego estaba influenciado por este artista y su obra. Y por último, la tercera sección aborda los movimientos campesinos y las luchas populares que culminaron con el movimiento Revolucionario de 1910.')
            .should('have.value', 'El primero hace referencia a la Conquista de México, la evangelización, la colonia, la Independencia de México, la Invasión Norteamericana, el gobierno de Santa Anna, la Intervención Francesa y la Reforma. El segundo se refiere a tres figuras centrales: el autoretrato de Diego Rivera a los 9 años, la Catrina y a José Guadalupe Posada. Diego estaba influenciado por este artista y su obra. Y por último, la tercera sección aborda los movimientos campesinos y las luchas populares que culminaron con el movimiento Revolucionario de 1910.')
        cy.get('#image')
            .type('https://storage.googleapis.com/principal-arena-219118/origenvida.jpg')
            .should('have.value', 'https://storage.googleapis.com/principal-arena-219118/origenvida.jpg')
        cy.contains('Crea Mural').click()  
    })
})